[package]
name = "simply-edit"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
terminal_size = "0.4"
image = "0.25"
indicatif = "0.17"
inquire = "0.9"
rayon = "1.10"
regex = "1.11"
resvg = "0.47"
vtracer = "0.6"

[[bin]]
name = "simply"
path = "src/main.rs"
